name: Call GitHub API

on:
  workflow_dispatch:  

jobs:
  call-github-api:
    runs-on: ubuntu-latest
    steps:
      - run: 'gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/komiya-atsushi/github-actions-playground/rules/branches/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
